testing validation script

diff --git a/.github/workflows/ex10-cd.yml b/.github/workflows/ex10-cd.yml
--- a/.github/workflows/ex10-cd.yml
+++ b/.github/workflows/ex10-cd.yml
@@ -109,23 +109,26 @@ jobs:
         run: | 
           ssh -i ~/.ssh/ec2_key ubuntu@${{ vars.EC2_IP }} "docker ps"
 
-      - name: Smoke test on EC2
+      # - name: Smoke test on EC2
+      #   run: |
+      #     ssh -i ~/.ssh/ec2_key ubuntu@${{ vars.EC2_IP }} "
+      #       for attempt in 1 2 3 4 5; do
+      #         if curl --fail --silent http://127.0.0.1:${{ env.APP_PORT }}/health; then
+      #           curl -o /dev/null -s -w '%{http_code}\n' http://127.0.0.1:${{ env.APP_PORT }}/health
+      #           exit 0
+      #         fi
+
+      #         curl -o /dev/null -s -w '%{http_code}\n' http://127.0.0.1:${{ env.APP_PORT }}/health
+      #         sleep 2
+      #       done
+
+      #       echo 'App did not become ready in time.'
+      #       exit 1
+      #     "
+      - name: Running validation script
         run: |
-          ssh -i ~/.ssh/ec2_key ubuntu@${{ vars.EC2_IP }} "
-            for attempt in 1 2 3 4 5; do
-              if curl --fail --silent http://127.0.0.1:${{ env.APP_PORT }}/health; then
-                curl -o /dev/null -s -w '%{http_code}\n' http://127.0.0.1:${{ env.APP_PORT }}/health
-                exit 0
-              fi
-
-              curl -o /dev/null -s -w '%{http_code}\n' http://127.0.0.1:${{ env.APP_PORT }}/health
-              sleep 2
-            done
-
-            echo 'App did not become ready in time.'
-            exit 1
-          "
-
+          bash scripts/assessment/validate-deployment.sh http://${{ vars.EC2_IP }}:8000
+          
       - name: Stop container
         if: always()
         # Clean up even if an earlier step fails.
