testing manual dpeloyment

diff --git a/.github/workflows/ex10-cd.yml b/.github/workflows/ex10-cd.yml
--- a/.github/workflows/ex10-cd.yml
+++ b/.github/workflows/ex10-cd.yml
@@ -6,24 +6,22 @@ on: # Listen for the build workflow by name.
       - closed
       branches:
       - main
+    workflow_dispatch:
       
 permissions:
   id-token: write
   contents: read
 
-# env:
 
 env:
   # Keep common image values in one place so the build steps stay readable.
   IMAGE_NAME: tiny-health-app
-  IMAGE_TAR: tiny-health-app.tar
-  ARTIFACT_NAME: tiny-health-app-image 
+  CONTAINER_NAME: tiny-health-container
+  APP_PORT: "8000"
   AWS_REGION: us-east-1
   ECR_REGISTRY: ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
   ECR_REPOSITORY: actions/lab
-  IMAGE_TAG: ${{ github.run_id }}
-  CONTAINER_NAME: tiny-health-container
-  APP_PORT: "8000"
+
 
 jobs:
   deploy-package:
@@ -35,52 +33,86 @@ jobs:
       - name: Configure AWS Credentials (OIDC)
         uses: aws-actions/configure-aws-credentials@v4
         with:
-            role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/actions-ecr
-            aws-region: ${{ env.AWS_REGION }}
-      
+          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/actions-ecr
+          aws-region: ${{ env.AWS_REGION }}
+
       - name: Fetch the caller identity
         run: | 
             aws sts get-caller-identity
-      - name: Login to ECR
+                      
+      - name: Prepare SSH
         run: |
-          aws ecr get-login-password --region $AWS_REGION \
-          | docker login --username AWS --password-stdin $ECR_REGISTRY
+          mkdir -p ~/.ssh
 
-      - name: Pull Docker Image
+          # Write private key
+          echo "$SSH_PRIVATE_KEY" > ~/.ssh/ec2_key
+          chmod 600 ~/.ssh/ec2_key
+
+          # Add EC2 host to known_hosts (prevents interactive prompt)
+          ssh-keyscan -H ${{ vars.EC2_IP }} >> ~/.ssh/known_hosts
+        shell: bash
+        env:
+          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
+
+
+        # SSH is working  
+   
+      - name: Testing SSH 
         run: |
-          docker pull $ECR_REGISTRY/$ECR_REPOSITORY:latest
+          ssh -i ~/.ssh/ec2_key ubuntu@${{ vars.EC2_IP }} \
+          "echo Connected && whoami && hostname" 
+
+      # Cloning the repository contents to copy scripts.
+      - name: Check out repository
+        uses: actions/checkout@v6
+      
+      - name: Copying & Executing scripts
+        run: |
+          scp -i ~/.ssh/ec2_key ./scripts/ ubuntu@${{ vars.EC2_IP }}:/tmp/
+          ssh -i ~/.ssh/ec2_key ubuntu@${{ vars.EC2_IP }} "chmod +x -R /tmp/scripts/"
+          ssh -i ~/.ssh/ec2_key ubuntu@${{ vars.EC2_IP }} "bash /tmp/scripts/assessment/prepare-ubuntu-vm.sh"
+         
+      
+      # - name: Login to ECR
+      #   run: |
+      #     aws ecr get-login-password --region $AWS_REGION \
+      #     | docker login --username AWS --password-stdin $ECR_REGISTRY
+
+      # - name: Pull Docker Image
+      #   run: |
+      #     docker pull $ECR_REGISTRY/$ECR_REPOSITORY:latest
           
-      - name: Show Current Images
-        run: | 
-          docker images 
+      # - name: Show Current Images
+      #   run: | 
+      #     docker images 
 
-      - name: Start container
-        # Start the exact same tagged image that the build workflow created.
-        run: |
-          docker run -d \
-            --name "${CONTAINER_NAME}" \
-            -p "${APP_PORT}:8000" \
-            "$ECR_REGISTRY/$ECR_REPOSITORY:latest"
+      # - name: Start container
+      #   # Start the exact same tagged image that the build workflow created.
+      #   run: |
+      #     docker run -d \
+      #       --name "${CONTAINER_NAME}" \
+      #       -p "${APP_PORT}:8000" \
+      #       "$ECR_REGISTRY/$ECR_REPOSITORY:latest"
 
-      - name: Show running container
-        run: | 
-          docker ps
+      # - name: Show running container
+      #   run: | 
+      #     docker ps
 
-      - name: Smoke test deployed app
-        # Retry a few times because app startup can take a moment.
-        run: |
-          for attempt in 1 2 3 4 5; do
-            if curl --fail --silent "http://127.0.0.1:${APP_PORT}/health"; then
-              echo "$(curl -o /dev/null -s -w "%{http_code}\n" http://127.0.0.1:${APP_PORT}/health)"
-              exit 0
-            fi
-            echo "$(curl -o /dev/null -s -w "%{http_code}\n" http://127.0.0.1:${APP_PORT}/health)"
-            sleep 2
-          done
-          echo "App did not become ready in time."
-          exit 1
+      # - name: Smoke test deployed app
+      #   # Retry a few times because app startup can take a moment.
+      #   run: |
+      #     for attempt in 1 2 3 4 5; do
+      #       if curl --fail --silent "http://127.0.0.1:${APP_PORT}/health"; then
+      #         echo "$(curl -o /dev/null -s -w "%{http_code}\n" http://127.0.0.1:${APP_PORT}/health)"
+      #         exit 0
+      #       fi
+      #       echo "$(curl -o /dev/null -s -w "%{http_code}\n" http://127.0.0.1:${APP_PORT}/health)"
+      #       sleep 2
+      #     done
+      #     echo "App did not become ready in time."
+      #     exit 1
 
-      - name: Stop container
-        if: always()
-        # Clean up even if an earlier step fails.
-        run: docker rm -f "${CONTAINER_NAME}" || true
+      # - name: Stop container
+      #   if: always()
+      #   # Clean up even if an earlier step fails.
+      #   run: docker rm -f "${CONTAINER_NAME}" || true
