testing full dpeloyment & cleanup

diff --git a/.github/workflows/ex10-cd.yml b/.github/workflows/ex10-cd.yml
--- a/.github/workflows/ex10-cd.yml
+++ b/.github/workflows/ex10-cd.yml
@@ -105,25 +105,28 @@ jobs:
             -p ${{ env.APP_PORT }}:8000 \
             ${ECR_REGISTRY}/${ECR_REPOSITORY}:latest"
 
-      # - name: Show running container
-      #   run: | 
-      #     docker ps
+      - name: Show running container
+        run: | 
+          ssh -i ~/.ssh/ec2_key ubuntu@${{ vars.EC2_IP }} "docker ps"
 
-      # - name: Smoke test deployed app
-      #   # Retry a few times because app startup can take a moment.
-      #   run: |
-      #     for attempt in 1 2 3 4 5; do
-      #       if curl --fail --silent "http://127.0.0.1:${APP_PORT}/health"; then
-      #         echo "$(curl -o /dev/null -s -w "%{http_code}\n" http://127.0.0.1:${APP_PORT}/health)"
-      #         exit 0
-      #       fi
-      #       echo "$(curl -o /dev/null -s -w "%{http_code}\n" http://127.0.0.1:${APP_PORT}/health)"
-      #       sleep 2
-      #     done
-      #     echo "App did not become ready in time."
-      #     exit 1
+      - name: Smoke test on EC2
+        run: |
+          ssh -i ~/.ssh/ec2_key ubuntu@${{ vars.EC2_IP }} "
+            for attempt in 1 2 3 4 5; do
+              if curl --fail --silent http://127.0.0.1:${{ env.APP_PORT }}/health; then
+                curl -o /dev/null -s -w '%{http_code}\n' http://127.0.0.1:${{ env.APP_PORT }}/health
+                exit 0
+              fi
 
-      # - name: Stop container
-      #   if: always()
-      #   # Clean up even if an earlier step fails.
-      #   run: docker rm -f "${CONTAINER_NAME}" || true
+              curl -o /dev/null -s -w '%{http_code}\n' http://127.0.0.1:${{ env.APP_PORT }}/health
+              sleep 2
+            done
+
+            echo 'App did not become ready in time.'
+            exit 1
+          "
+
+      - name: Stop container
+        if: always()
+        # Clean up even if an earlier step fails.
+        run: ssh -i ~/.ssh/ec2_key ubuntu@${{ vars.EC2_IP }} "docker rm -f "${CONTAINER_NAME}" || true"
